package org.campagnelab.nyosh.gstring.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;

public class GString_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
    int i = 0;
    for (SNode component : ListSequence.fromList(SLinkOperations.getTargets(node, "components", true))) {
      this.append(BehaviorReflection.invokeVirtual(String.class, component, "virtual_literal_4087517305356282226", new Object[]{}));
      boolean end = i >= ListSequence.fromList(SLinkOperations.getTargets(node, "components", true)).count() - 1;
      if (!(end)) {
        this.append("+");
      }
      i++;
    }
  }
}
