package org.campagnelab.nyosh.gstring.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.smodel.behaviour.BehaviorManager;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class GStringComponent_Behavior {
  public static void init(SNode thisNode) {
  }

  @Deprecated
  public static String call_literal_4087517305356282226(SNode thisNode) {
    return BehaviorReflection.invokeVirtual(String.class, thisNode, "virtual_literal_4087517305356282226", new Object[]{});
  }

  @Deprecated
  public static String callSuper_literal_4087517305356282226(SNode thisNode, String callerConceptFqName) {
    return BehaviorManager.getInstance().invokeSuper(String.class, SNodeOperations.cast(thisNode, "org.campagnelab.nyosh.gstring.structure.GStringComponent"), callerConceptFqName, "virtual_literal_4087517305356282226", new Class[]{SNode.class}, new Object[]{});
  }
}
