package org.campagnelab.textoutput.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class TextOutput_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
    OutputToText.textOutput(node, this);
  }
  public String getExtension(SNode node) {
    return SPropertyOperations.getString(node, MetaAdapterFactory.getProperty(0x901f5cf3dc774c1eL, 0xbc5a6382baee28b4L, 0x5f67f81c22d111cbL, 0x3b63a891ae48b5d6L, "extension"));
  }
}
