package NYoSh.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.generator.template.CreateRootRuleContext;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;
import jetbrains.mps.generator.template.BaseMappingRuleContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.baseLanguage.behavior.ClassConcept_Behavior;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.generator.template.ReferenceMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.generator.template.IfMacroContext;
import jetbrains.mps.baseLanguage.behavior.Classifier_Behavior;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import jetbrains.mps.generator.template.TemplateQueryContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import jetbrains.mps.internal.collections.runtime.ITranslator2;
import jetbrains.mps.internal.collections.runtime.ISelector;
import jetbrains.mps.generator.template.TemplateFragmentContext;
import jetbrains.mps.generator.template.WeavingMappingRuleContext;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class QueriesGenerated {
  public static boolean createRootRule_Condition_2010614965247312410(final IOperationContext operationContext, final CreateRootRuleContext _context) {
    // Create a dummy error management node if none was provided explicitly 
    return ListSequence.fromList(SModelOperations.getRoots(_context.getOriginalInputModel(), "NYoSh.structure.ErrorManagement")).isEmpty();
  }

  public static boolean baseMappingRule_Condition_3999230645370603588(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    if (SNodeOperations.getParent(_context.getNode()) == null && ListSequence.fromList(SNodeOperations.getDescendants(_context.getNode(), "NYoSh.structure.ISomeStepLoggingStatement", false, new String[]{})).isNotEmpty()) {
      if (ListSequence.fromList(SNodeOperations.getDescendants(_context.getNode(), "NYoSh.structure.StepsLoggerDeclared", false, new String[]{})).isEmpty()) {
        return true;
      }
    }
    return false;
    // <node> 
  }

  public static boolean baseMappingRule_Condition_4907898740900732088(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SPropertyOperations.getBoolean(_context.getNode(), "consumeStandardOutput");
  }

  public static boolean baseMappingRule_Condition_4907898740900775119(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SPropertyOperations.getBoolean(_context.getNode(), "consumeStandardOutput");
  }

  public static boolean baseMappingRule_Condition_4907898740900909782(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SPropertyOperations.getBoolean(_context.getNode(), "consumeStandardError");
  }

  public static boolean baseMappingRule_Condition_4907898740901038182(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SPropertyOperations.getBoolean(_context.getNode(), "consumeStandardError");
  }

  public static boolean baseMappingRule_Condition_4907898740901275816(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SPropertyOperations.getBoolean(_context.getNode(), "consumeStandardOutput");
  }

  public static boolean baseMappingRule_Condition_7518874264088361664(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SNodeOperations.getParent(_context.getNode()) == null && ListSequence.fromList(SNodeOperations.getDescendants(_context.getNode(), "NYoSh.structure.ISomeErrorUsage", false, new String[]{})).isNotEmpty() && !(Sequence.fromIterable(ClassConcept_Behavior.call_fields_5292274854859383272(_context.getNode())).any(new IWhereFilter<SNode>() {
      public boolean accept(SNode f) {
        return SPropertyOperations.getString(f, "name").equals("errorManagement");
      }
    }));
  }

  public static boolean baseMappingRule_Condition_2010614965249460538(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    // Only report exceptions when error management is defined 
    return ListSequence.fromList(SModelOperations.getRoots(_context.getOriginalInputModel(), "NYoSh.structure.ErrorManagement")).isNotEmpty();
  }

  public static boolean baseMappingRule_Condition_2010614965249549323(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    // Only report exceptions when error management is defined 
    return ListSequence.fromList(SModelOperations.getRoots(_context.getOriginalInputModel(), "NYoSh.structure.ErrorManagement")).isNotEmpty();
  }

  public static boolean baseMappingRule_Condition_2010614965249905459(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return ListSequence.fromList(SModelOperations.getRoots(_context.getOriginalInputModel(), "NYoSh.structure.ErrorManagement")).isEmpty();
  }

  public static boolean baseMappingRule_Condition_2010614965249966423(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return ListSequence.fromList(SModelOperations.getRoots(_context.getOriginalInputModel(), "NYoSh.structure.ErrorManagement")).isEmpty();
  }

  public static boolean baseMappingRule_Condition_3999230645377280339(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    // Testing if the Script was already converted to a root class: 
    // We need this condition because Script can be either root or non-root node 
    // e.g., non root when referenced within a GobyWeb plugin 
    boolean result = !(ListSequence.fromList(SModelOperations.getRoots(_context.getInputModel(), "jetbrains.mps.baseLanguage.structure.ClassConcept")).any(new IWhereFilter<SNode>() {
      public boolean accept(SNode script) {
        return SPropertyOperations.getString(script, "name").equals(SPropertyOperations.getString(_context.getNode(), "name"));
      }
    }));
    return result;
  }

  public static Object propertyMacro_GetPropertyValue_6431787771175670708(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_8483436209635881989(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_7872582389600940400(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "alias");
  }

  public static Object propertyMacro_GetPropertyValue_435930706556389111(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "description");
  }

  public static Object propertyMacro_GetPropertyValue_435930706556389138(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return _context.createUniqueName("success", _context.getNode());
  }

  public static Object propertyMacro_GetPropertyValue_435930706556389155(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "description");
  }

  public static Object propertyMacro_GetPropertyValue_435930706556389162(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return _context.createUniqueName("reason", _context.getNode());
  }

  public static Object propertyMacro_GetPropertyValue_5787209143228213122(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return _context.createUniqueName("exception", SNodeOperations.getAncestor(_context.getNode(), "jetbrains.mps.baseLanguage.structure.BlockStatement", false, false));
  }

  public static Object propertyMacro_GetPropertyValue_385706599061325611(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_9039864166930640540(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return _context.createUniqueName(SPropertyOperations.getString(_context.getNode(), "name"), _context.getNode());
  }

  public static Object propertyMacro_GetPropertyValue_7507736014962008517(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return _context.createUniqueName(SPropertyOperations.getString(_context.getNode(), "name"), _context.getNode());
  }

  public static Object propertyMacro_GetPropertyValue_9039864166930247303(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return _context.createUniqueName(SPropertyOperations.getString(_context.getNode(), "name"), null);
  }

  public static Object propertyMacro_GetPropertyValue_7507736014961255884(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return _context.createUniqueName(SPropertyOperations.getString(_context.getNode(), "name"), null);
  }

  public static Object referenceMacro_GetReferent_7518874264096829674(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return "arguments";
    // <node> 
  }

  public static Object referenceMacro_GetReferent_4927548581349126141(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    if (SNodeOperations.isInstanceOf(_context.getNode(), "NYoSh.structure.ChangeDirectory")) {
      return "changeDirectory";
    }
    if (SNodeOperations.isInstanceOf(_context.getNode(), "NYoSh.structure.BashFragment")) {
      return "appendBashFragment";
    }
    return (SNodeOperations.isInstanceOf(_context.getNode(), "NYoSh.structure.GStringCommand") ?
      "appendCommand" :
      "appendOperator"
    );
  }

  public static Object referenceMacro_GetReferent_7414196263097490723(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SNodeOperations.cast(ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "commands", true)).last(), "NYoSh.structure.PutResultInVariable"), "variable", false), "name");
  }

  public static Object referenceMacro_GetReferent_9213669739149152106(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return "fail";
  }

  public static Object referenceMacro_GetReferent_9039864166929501704(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return "fail";
  }

  public static Object referenceMacro_GetReferent_9039864166928527666(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return "done";
  }

  public static Object referenceMacro_GetReferent_4907898740901298345(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    if (SPropertyOperations.getBoolean(_context.getNode(), "consumeStandardOutput")) {
      return "consumeStandardOutput";
    } else if (SPropertyOperations.getBoolean(_context.getNode(), "consumeStandardError")) {
      return "consumeStandardError";
    }
    return "undefinedMethod";
  }

  public static Object referenceMacro_GetReferent_7507736014961274012(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SLinkOperations.getTarget(_context.getNode(), "handler", false), "method_SuccessHandler");
  }

  public static Object referenceMacro_GetReferent_9039864166931916245(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SLinkOperations.getTarget(_context.getNode(), "handler", false), "method_ErrorHandler");
  }

  public static Object referenceMacro_GetReferent_9039864166931122960(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getOutputNodeByInputNodeAndMappingLabel(SLinkOperations.getTarget(_context.getNode(), "handler", false), "method_ErrorHandler"), "name");
  }

  public static Object referenceMacro_GetReferent_7507736014961225987(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SLinkOperations.getTarget(_context.getNode(), "handler", false), "method_SuccessHandler");
  }

  public static boolean ifMacro_Condition_7414196263098247788(final IOperationContext operationContext, final IfMacroContext _context) {
    SNode lastCommand = ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "commands", true)).last();
    return SNodeOperations.isInstanceOf(lastCommand, "NYoSh.structure.PutResultInVariable") && SPropertyOperations.getBoolean(SNodeOperations.cast(lastCommand, "NYoSh.structure.PutResultInVariable"), "consumeStandardOutput");
  }

  public static boolean ifMacro_Condition_5949986731306071704(final IOperationContext operationContext, final IfMacroContext _context) {
    return Sequence.fromIterable(Classifier_Behavior.call_staticFields_5292274854859223538(SNodeOperations.getAncestor(_context.getNode(), "jetbrains.mps.baseLanguage.structure.ClassConcept", false, false))).any(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SPropertyOperations.getString(it, "name").equals("exportedVariables");
      }
    });
  }

  public static boolean ifMacro_Condition_4325409482886268091(final IOperationContext operationContext, final IfMacroContext _context) {
    return !(SPropertyOperations.getBoolean(_context.getNode(), "ignoreErrors"));
  }

  public static boolean ifMacro_Condition_7855977029128093197(final IOperationContext operationContext, final IfMacroContext _context) {
    return SPropertyOperations.getBoolean(_context.getNode(), "printExecutedToStdout");
  }

  public static boolean ifMacro_Condition_9138295635397069272(final IOperationContext operationContext, final IfMacroContext _context) {
    SNode lastCommand = ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "commands", true)).last();
    return SNodeOperations.isInstanceOf(lastCommand, "NYoSh.structure.PutResultInVariable") && SPropertyOperations.getBoolean(SNodeOperations.cast(lastCommand, "NYoSh.structure.PutResultInVariable"), "consumeStandardOutput");
  }

  public static boolean ifMacro_Condition_435930706556389241(final IOperationContext operationContext, final IfMacroContext _context) {
    return ListSequence.fromList(SNodeOperations.getAncestors(_context.getNode(), "NYoSh.structure.StepMarker", false)).isEmpty();
  }

  public static SNode sourceNodeQuery_7518874264101893446(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "prototype", true);
  }

  public static SNode sourceNodeQuery_2829258213791012152(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "implementation", true);
  }

  public static SNode sourceNodeQuery_7872582389600940237(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "command", true);
  }

  public static SNode sourceNodeQuery_6839116863307682695(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "path", true);
  }

  public static SNode sourceNodeQuery_4907898740900727222(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    SNode lastCommand = ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "commands", true)).last();
    return lastCommand;
  }

  public static SNode sourceNodeQuery_3834344539456361046(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "message", true);
  }

  public static SNode sourceNodeQuery_3834344539458185979(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "statusCode", true);
  }

  public static SNode sourceNodeQuery_435930706556388982(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return _context.getNode();
  }

  public static SNode sourceNodeQuery_435930706556389034(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "expression", true);
  }

  public static SNode sourceNodeQuery_3834344539456372649(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "message", true);
  }

  public static SNode sourceNodeQuery_435930706556389179(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return _context.getNode();
  }

  public static SNode sourceNodeQuery_3834344539457451313(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "message", true);
  }

  public static SNode sourceNodeQuery_3834344539457522265(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "statusCode", true);
  }

  public static SNode sourceNodeQuery_4907898740900748877(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(SNodeOperations.cast(_context.getNode(), "NYoSh.structure.ConsumeCommandOutputWithStream"), "streamExpression", true), "body", true);
  }

  public static SNode sourceNodeQuery_4927548581349126362(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "readerExpression", true), "body", true);
  }

  public static SNode sourceNodeQuery_4927548581349126292(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "streamExpression", true), "body", true);
  }

  public static SNode sourceNodeQuery_4907898740901061388(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "readerExpression", true), "body", true);
  }

  public static SNode sourceNodeQuery_4907898740901250605(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "filename", true);
  }

  public static SNode sourceNodeQuery_6449713081305649196(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "fragment", true);
  }

  public static SNode sourceNodeQuery_9039864166931224346(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "handlerFunction", true), "body", true);
  }

  public static SNode sourceNodeQuery_3941135000200420694(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "expression", true);
  }

  public static SNode sourceNodeQuery_224223098167714864(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SNodeOperations.getAncestor(_context.getNode(), "jetbrains.mps.baseLanguage.structure.ClassConcept", false, false);
  }

  public static SNode sourceNodeQuery_7518874264089020327(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "reason", true);
  }

  public static SNode sourceNodeQuery_7518874264089020773(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    if ((SLinkOperations.getTarget(_context.getNode(), "exception", true) != null)) {
      return SLinkOperations.getTarget(_context.getNode(), "exception", true);
    } else {
      return _quotation_createNode_x583g4_a0a0a0oc();
    }
  }

  public static SNode sourceNodeQuery_7518874264089019492(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "message", true);
  }

  public static SNode sourceNodeQuery_7507736014961255871(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "handlerFunction", true), "body", true);
  }

  public static Object templateArgumentQuery_7518874264102333268(final IOperationContext operationContext, final TemplateQueryContext _context) {
    return ((String) _context.getGenerationParameter("r:ab86e397-1503-48ca-8931-8dc598446fee.EntryPointImplementationName.implementationMethodName"));
  }

  public static Iterable sourceNodesQuery_6431787771175731896(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "entryPoints", true);
  }

  public static Iterable sourceNodesQuery_2829258213790991045(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "entryPoints", true);
  }

  public static Iterable sourceNodesQuery_4927548581349126164(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "commands", true)).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SNodeOperations.isInstanceOf(it, "NYoSh.structure.GStringCommand") || SNodeOperations.isInstanceOf(it, "NYoSh.structure.BinaryCommandOperator") || SNodeOperations.isInstanceOf(it, "NYoSh.structure.ChangeDirectory") || SNodeOperations.isInstanceOf(it, "NYoSh.structure.BashFragment");

      }
    });
  }

  public static Iterable sourceNodesQuery_3834344539456229802(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "commands", true)).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SNodeOperations.isInstanceOf(it, "NYoSh.structure.GStringCommand") || SNodeOperations.isInstanceOf(it, "NYoSh.structure.BinaryCommandOperator") || SNodeOperations.isInstanceOf(it, "NYoSh.structure.ChangeDirectory");

      }
    });
  }

  public static Iterable sourceNodesQuery_7015383683230037427(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(SLinkOperations.getTarget(_context.getNode(), "body", true), "statement", true);
  }

  public static Iterable sourceNodesQuery_385706599061303293(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "parameter", true);
  }

  public static Iterable sourceNodesQuery_7507736014961274022(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return ListSequence.fromList(SModelOperations.getRoots(_context.getInputModel(), "NYoSh.structure.ErrorManagement")).translate(new ITranslator2<SNode, SNode>() {
      public Iterable<SNode> translate(SNode it) {
        return SLinkOperations.getTargets(it, "successHandler", true);
      }
    });
  }

  public static Iterable sourceNodesQuery_9039864166931848938(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return ListSequence.fromList(SModelOperations.getRoots(_context.getInputModel(), "NYoSh.structure.ErrorManagement")).translate(new ITranslator2<SNode, SNode>() {
      public Iterable<SNode> translate(SNode it) {
        return SLinkOperations.getTargets(it, "errorHandlers", true);
      }
    });
  }

  public static Iterable sourceNodesQuery_4236149660851124421(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "handlerFunction", true), "body", true), "statement", true);
  }

  public static Iterable sourceNodesQuery_9039864166930647622(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return ListSequence.fromList(SModelOperations.getRoots(_context.getInputModel(), "NYoSh.structure.ErrorManagement")).translate(new ITranslator2<SNode, SNode>() {
      public Iterable<SNode> translate(SNode it) {
        return SLinkOperations.getTargets(it, "errorHandlers", true);
      }
    }).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return (SLinkOperations.getTarget(it, "handler", false) != null);
      }
    }).select(new ISelector<SNode, SNode>() {
      public SNode select(SNode it) {
        return SLinkOperations.getTarget(it, "handler", false);
      }
    });
  }

  public static Iterable sourceNodesQuery_7507736014962008500(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "handlerFunction", true), "body", true), "statement", true);
  }

  public static Iterable sourceNodesQuery_7507736014962008528(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return ListSequence.fromList(SModelOperations.getRoots(_context.getInputModel(), "NYoSh.structure.ErrorManagement")).translate(new ITranslator2<SNode, SNode>() {
      public Iterable<SNode> translate(SNode it) {
        return SLinkOperations.getTargets(it, "successHandler", true);
      }
    }).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return (SLinkOperations.getTarget(it, "handler", false) != null);
      }
    }).select(new ISelector<SNode, SNode>() {
      public SNode select(SNode it) {
        return SLinkOperations.getTarget(it, "handler", false);
      }
    });
  }

  public static SNode templateFragment_ContextNodeQuery_7518874264096951530(final IOperationContext operationContext, final TemplateFragmentContext _context) {
    return _context.getMainContextNode();
  }

  public static SNode weaving_MappingRule_ContextNodeQuery_3999230645370198099(final IOperationContext opereationContext, final WeavingMappingRuleContext _context) {
    SNode stepStatement = ListSequence.fromList(SNodeOperations.getDescendants(_context.getNode(), "NYoSh.structure.ISomeStepLoggingStatement", false, new String[]{})).first();
    SNode usage = _context.getOutputNodeByInputNodeAndMappingLabel(stepStatement, "usage_stepsLogger");
    SNode ancestor = SNodeOperations.getAncestor(usage, "jetbrains.mps.baseLanguage.structure.ClassConcept", false, true);
    if (ancestor != null) {
      return ancestor;
    }

    SNode outputNode = _context.getCopiedOutputNodeForInputNode(_context.getNode());
    if (outputNode == null) {
      _context.showErrorMessage(_context.getNode(), "Can't find copy of the class concept in the target model");
    }
    return outputNode;
  }

  public static SNode weaving_MappingRule_ContextNodeQuery_7518874264088361608(final IOperationContext opereationContext, final WeavingMappingRuleContext _context) {
    SNode stepStatement = ListSequence.fromList(SNodeOperations.getDescendants(_context.getNode(), "NYoSh.structure.ISomeErrorUsage", false, new String[]{})).first();
    SNode usage = _context.getOutputNodeByInputNodeAndMappingLabel(stepStatement, "usage_Errors");
    SNode ancestor = SNodeOperations.getAncestor(usage, "jetbrains.mps.baseLanguage.structure.ClassConcept", false, true);
    if (ancestor != null) {
      return ancestor;
    }

    SNode outputNode = _context.getCopiedOutputNodeForInputNode(_context.getNode());
    if (outputNode == null) {
      _context.showErrorMessage(_context.getNode(), "Can't find copy of the class concept in the target model");
    }
    return outputNode;
  }

  public static Object insertMacro_varValue_7518874264101001566(final IOperationContext operationContext, final TemplateQueryContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "implementation", true), "name");
  }

  private static SNode _quotation_createNode_x583g4_a0a0a0oc() {
    PersistenceFacade facade = PersistenceFacade.getInstance();
    SNode quotedNode_1 = null;
    quotedNode_1 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.structure.NullLiteral", null, null, GlobalScope.getInstance(), false);
    return quotedNode_1;
  }
}
