package org.campagnelab.nyosh.gstring.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.runtime.StaticScope;
import jetbrains.mps.smodel.runtime.interpreted.StructureAspectInterpreted;

public class StructureAspectDescriptor implements jetbrains.mps.smodel.runtime.StructureAspectDescriptor {
  public StructureAspectDescriptor() {
  }

  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0b, conceptFqName)) {
      case 0:
        return new ConceptDescriptorBuilder("org.campagnelab.nyosh.gstring.structure.GString").super_("jetbrains.mps.baseLanguage.structure.Expression").parents("jetbrains.mps.baseLanguage.structure.Expression").children(new String[]{"components"}, new boolean[]{true}).alias("gstring", "GStrings support embedded variable references, for instance \"some text ${var}\" will be a valid GString if var was defined in the scope of the expression.").create();
      case 1:
        return new ConceptDescriptorBuilder("org.campagnelab.nyosh.gstring.structure.GStringComponent").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept").abstract_().staticScope(StaticScope.ROOT).create();
      case 2:
        return new ConceptDescriptorBuilder("org.campagnelab.nyosh.gstring.structure.GStringLiteral").super_("org.campagnelab.nyosh.gstring.structure.GStringComponent").parents("org.campagnelab.nyosh.gstring.structure.GStringComponent").properties("value").alias("literal", "").create();
      case 3:
        return new ConceptDescriptorBuilder("org.campagnelab.nyosh.gstring.structure.GStringVarReference").super_("org.campagnelab.nyosh.gstring.structure.GStringComponent").parents("org.campagnelab.nyosh.gstring.structure.GStringComponent").references("varRef").create();
      default:
        return StructureAspectInterpreted.getInstance().getDescriptor(conceptFqName);
    }
  }

  private static String[] stringSwitchCases_1htk8d_a0a0b = new String[]{"org.campagnelab.nyosh.gstring.structure.GString", "org.campagnelab.nyosh.gstring.structure.GStringComponent", "org.campagnelab.nyosh.gstring.structure.GStringLiteral", "org.campagnelab.nyosh.gstring.structure.GStringVarReference"};
}
