package org.campagnelab.gobyweb.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import jetbrains.mps.smodel.SModelUtil_new;
import org.jetbrains.mps.openapi.model.SNodeAccessUtil;

public class AlignmentAnalysisNumPartsEntryPoint_Behavior {
  public static void init(SNode thisNode) {
    SPropertyOperations.set(thisNode, "name", "plugin_alignment_analysis_num_parts");
    SLinkOperations.setTarget(thisNode, "implementation", _quotation_createNode_vgjo7x_a0b0a(), true);
    SLinkOperations.setTarget(thisNode, "prototype", SConceptOperations.createNewNode("org.campagnelab.gobyweb.structure.AlignmentAnalysisNumPartsPrototype", null), true);
    GobyWebEntryPoint_Behavior.call_addInitStatementsToImplementation_6225477831023821668(thisNode, SLinkOperations.getTarget(thisNode, "implementation", true));
  }

  private static SNode _quotation_createNode_vgjo7x_a0b0a() {
    PersistenceFacade facade = PersistenceFacade.getInstance();
    SNode quotedNode_1 = null;
    SNode quotedNode_2 = null;
    SNode quotedNode_3 = null;
    SNode quotedNode_4 = null;
    SNode quotedNode_5 = null;
    SNode quotedNode_6 = null;
    quotedNode_1 = SModelUtil_new.instantiateConceptDeclaration("org.campagnelab.NYoSh.structure.StaticEntryPointMethod", null, null, false);
    SNodeAccessUtil.setProperty(quotedNode_1, "name", "numParts");
    quotedNode_2 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.structure.ParameterDeclaration", null, null, false);
    SNodeAccessUtil.setProperty(quotedNode_2, "name", "splicingPlanFile");
    quotedNode_6 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.structure.StringType", null, null, false);
    quotedNode_2.addChild("type", quotedNode_6);
    quotedNode_1.addChild("parameter", quotedNode_2);
    quotedNode_3 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.structure.VoidType", null, null, false);
    quotedNode_1.addChild("returnType", quotedNode_3);
    quotedNode_4 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.structure.PublicVisibility", null, null, false);
    quotedNode_1.addChild("visibility", quotedNode_4);
    quotedNode_5 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.structure.StatementList", null, null, false);
    quotedNode_1.addChild("body", quotedNode_5);
    return quotedNode_1;
  }
}
