package org.campagnelab.gobyweb.behavior;

/*Generated by MPS */


public class AlignmentAnalysisNumPartsEntryPoint_BehaviorDescriptor extends GobyWebEntryPoint_BehaviorDescriptor {
  public AlignmentAnalysisNumPartsEntryPoint_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.gobyweb.structure.AlignmentAnalysisNumPartsEntryPoint";
  }
}
