package org.campagnelab.gobyweb.behavior;

/*Generated by MPS */


public class AlignmentAnalysisScript_BehaviorDescriptor extends PluginScript_BehaviorDescriptor {
  public AlignmentAnalysisScript_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.gobyweb.structure.AlignmentAnalysisScript";
  }
}
