package org.campagnelab.gobyweb.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import jetbrains.mps.smodel.SModelUtil_new;
import org.jetbrains.mps.openapi.model.SNodeAccessUtil;

public class ArtifactAttributeValuesEntryPoint_Behavior {
  public static void init(SNode thisNode) {
    SPropertyOperations.set(thisNode, "name", "get_attribute_values");
    SLinkOperations.setTarget(thisNode, "prototype", SConceptOperations.createNewNode("org.campagnelab.gobyweb.structure.ArtifactAttributeValuesEntryPointPrototype", null), true);
    SLinkOperations.setTarget(thisNode, "implementation", _quotation_createNode_vw6m4z_a0c0a(), true);
    GobyWebEntryPoint_Behavior.call_addInitStatementsToImplementation_6225477831023821668(thisNode, SLinkOperations.getTarget(thisNode, "implementation", true));
  }

  private static SNode _quotation_createNode_vw6m4z_a0c0a() {
    PersistenceFacade facade = PersistenceFacade.getInstance();
    SNode quotedNode_1 = null;
    SNode quotedNode_2 = null;
    SNode quotedNode_3 = null;
    SNode quotedNode_4 = null;
    quotedNode_1 = SModelUtil_new.instantiateConceptDeclaration("org.campagnelab.NYoSh.structure.StaticEntryPointMethod", null, null, false);
    SNodeAccessUtil.setProperty(quotedNode_1, "name", "get_attribute_values");
    quotedNode_2 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.structure.VoidType", null, null, false);
    quotedNode_1.addChild("returnType", quotedNode_2);
    quotedNode_3 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.structure.PublicVisibility", null, null, false);
    quotedNode_1.addChild("visibility", quotedNode_3);
    quotedNode_4 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.structure.StatementList", null, null, false);
    quotedNode_1.addChild("body", quotedNode_4);
    return quotedNode_1;
  }
}
