package org.campagnelab.gobyweb.behavior;

/*Generated by MPS */


public class ArtifactInstallEntryPoint_BehaviorDescriptor extends GobyWebEntryPoint_BehaviorDescriptor {
  public ArtifactInstallEntryPoint_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.gobyweb.structure.ArtifactInstallEntryPoint";
  }
}
