package org.campagnelab.gobyweb.behavior;

/*Generated by MPS */


public class ErrorManagementImplementation {
  public void recordStepDone(String actionDescription) {

  }

  public void exception(String actionDescription, int statusCode, Exception exception) {
  }



}
