package org.campagnelab.gobyweb.behavior;

/*Generated by MPS */


public class FileSetPushExpression_BehaviorDescriptor extends FileSetExpression_BehaviorDescriptor {
  public FileSetPushExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.gobyweb.structure.FileSetPushExpression";
  }
}
