package org.campagnelab.gobyweb.behavior;

/*Generated by MPS */


public class FileSetFetchExpression_BehaviorDescriptor extends FileSetExpression_BehaviorDescriptor {
  public FileSetFetchExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.gobyweb.structure.FileSetFetchExpression";
  }
}
