package org.campagnelab.gobyweb.behavior;

/*Generated by MPS */


public class FileSetFetchCommand_BehaviorDescriptor extends FileSetCommand_BehaviorDescriptor {
  public FileSetFetchCommand_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.gobyweb.structure.FileSetFetchCommand";
  }
}
