package org.campagnelab.gobyweb.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class PluginScript_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public PluginScript_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.gobyweb.structure.PluginScript";
  }
}
