package org.campagnelab.gobyweb.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class PluginTree_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public PluginTree_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.gobyweb.structure.PluginTree";
  }
}
