package org.campagnelab.gobyweb.behavior;

/*Generated by MPS */


public class ResourceWithArtifactScript_BehaviorDescriptor extends PluginScript_BehaviorDescriptor {
  public ResourceWithArtifactScript_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.gobyweb.structure.ResourceWithArtifactScript";
  }
}
