package org.campagnelab.gobyweb.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import java.util.List;
import java.util.ArrayList;

public class TaskEntryPointPrototype_Behavior {
  public static void init(SNode thisNode) {
    SPropertyOperations.set(thisNode, "header", "task entry point");
    SPropertyOperations.set(thisNode, "implementationMethodName", "plugin_task");
  }

  public static List<SNode> virtual_parameters_2829258213786778419(SNode thisNode) {
    List<SNode> parameters = new ArrayList<SNode>();
    return parameters;
  }
}
