package org.campagnelab.gobyweb.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.IntentionFactory;
import java.util.Collection;
import jetbrains.mps.intentions.IntentionExecutable;
import jetbrains.mps.intentions.IntentionType;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import java.util.Collections;
import org.campagnelab.gobyweb.behavior.GobyWebEntryPoint_Behavior;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.intentions.IntentionDescriptor;

public class AddEnvironmentSupport_Intention implements IntentionFactory {
  private Collection<IntentionExecutable> myCachedExecutable;

  public AddEnvironmentSupport_Intention() {
  }

  public String getConcept() {
    return "org.campagnelab.gobyweb.structure.GobyWebEntryPoint";
  }

  public String getPresentation() {
    return "AddEnvironmentSupport";
  }

  public String getPersistentStateKey() {
    return "org.campagnelab.gobyweb.intentions.AddEnvironmentSupport_Intention";
  }

  public String getLanguageFqName() {
    return "org.campagnelab.gobyweb";
  }

  public IntentionType getType() {
    return IntentionType.NORMAL;
  }

  public boolean isAvailableInChildNodes() {
    return false;
  }

  public boolean isApplicable(final SNode node, final EditorContext editorContext) {
    return true;
  }

  public SNodeReference getIntentionNodeReference() {
    return new SNodePointer("r:c13e4aa8-3534-477b-bcd1-e8b38e45f88a(org.campagnelab.gobyweb.intentions)", "6225477831026116064");
  }

  public boolean isSurroundWith() {
    return false;
  }

  public Collection<IntentionExecutable> instances(final SNode node, final EditorContext context) {
    if (myCachedExecutable == null) {
      myCachedExecutable = Collections.<IntentionExecutable>singletonList(new AddEnvironmentSupport_Intention.IntentionImplementation());
    }
    return myCachedExecutable;
  }

  public class IntentionImplementation implements IntentionExecutable {
    public IntentionImplementation() {
    }

    public String getDescription(final SNode node, final EditorContext editorContext) {
      return "Add Environment Parsing Code to an Entry Point";
    }

    public void execute(final SNode node, final EditorContext editorContext) {
      GobyWebEntryPoint_Behavior.call_addInitStatementsToImplementation_6225477831023821668(node, SLinkOperations.getTarget(node, "implementation", true));
    }

    public IntentionDescriptor getDescriptor() {
      return AddEnvironmentSupport_Intention.this;
    }
  }
}
