package NYoSh.sandbox.HelloWorld;

/*Generated by MPS */

import org.campagnelab.nyosh.exec.CommandAssembler;

public class HelloWorld {
  public static void main(String[] arguments) {
    String command = "ls";
    String option = "-ltr";
    {
      CommandAssembler assembler = new CommandAssembler();
      assembler.appendCommand(command+" "+option);
      assembler.finishAssembly();
      assembler.getCommandExecutionPlan().run();
    }
    {
      CommandAssembler assembler = new CommandAssembler();
      assembler.appendCommand("ls");
      assembler.finishAssembly();
      assembler.getCommandExecutionPlan().run();
    }
    int a = 3;
    String b = "BGG";
    System.out.println("b:" + b);
    String s = b+"aaa";
    {
      CommandAssembler assembler = new CommandAssembler();
      assembler.appendCommand("ls");
      assembler.finishAssembly();
      assembler.getCommandExecutionPlan().run();
    }
    System.out.println("a:" + a);
  }
}
