package NYoSh.sandbox.HelloWorld;

/*Generated by MPS */

import java.io.InputStream;
import java.io.BufferedReader;
import java.io.InputStreamReader;

public class HelloWorld {
  public static void main(String[] arguments) {
    String command = "ls";
    String option = "-ltr";
    {
      String commandLine = command+" "+option;
      try {
        System.out.println("executing: " + commandLine);
        Process p = Runtime.getRuntime().exec(commandLine.split(" "));
        {
          // consume stream  
          InputStream stream = p.getInputStream();
        }

        p.waitFor();

        if (p.exitValue() != 0) {
        }

      } catch (Exception e) {
      }
    }
    {
      String commandLine = "ls";
      try {
        System.out.println("executing: " + commandLine);
        Process p = Runtime.getRuntime().exec(commandLine.split(" "));

        p.waitFor();

        if (p.exitValue() != 0) {
        }

      } catch (Exception e) {
      }
    }
    int a = 3;
    String b = "BGG";
    System.out.println("b:" + b);
    String s = b+"aaa";
    {
      String commandLine = "ls";
      try {
        System.out.println("executing: " + commandLine);
        Process p = Runtime.getRuntime().exec(commandLine.split(" "));
        {
          // consume reader 
          InputStream stream = p.getInputStream();
          BufferedReader reader = new BufferedReader(new InputStreamReader(stream));
          String line;
          while ((line = reader.readLine()) != null) {
            System.out.println("line:" + line);
          }
        }

        p.waitFor();

        if (p.exitValue() != 0) {
        }

      } catch (Exception e) {
      }
    }
    System.out.println("a:" + a);
  }
}
