package org.campagnelab.gobyweb.charts.SequenceVariations;

/*Generated by MPS */

import java.util.ArrayList;
import com.xeiam.xchart.Chart;
import com.xeiam.xchart.ChartBuilder;
import com.xeiam.xchart.StyleManager;
import org.campagnelab.mps.XChart.helpers.DoublesToCollection;
import org.campagnelab.mps.XChart.helpers.ColumnLoader;
import org.campagnelab.mps.XChart.helpers.CustomSwingWrapper;
import javax.swing.JFrame;
import javax.swing.JPanel;

public class ChartViewer_QualityStatsScatterPlot {
  public static ArrayList<Chart> buildCharts(String... filenames) {
    ArrayList<Chart> charts = new ArrayList<Chart>();
    int filenameIndex = 0;
    int numCharts = 1;
    {
      Chart chart = null;
      String filename = filenames[filenameIndex];
      {
        // ScaterPlot 

        double[] xs = null;
        chart = new ChartBuilder().chartType(StyleManager.ChartType.Scatter).width(600).height(400).theme(StyleManager.ChartTheme.GGPlot2).title("Read Quality Scores").xAxisTitle("Read Index (Cycle)").yAxisTitle("Quality Score (Phred Scale)").build();
        chart.getStyleManager().setYAxisMin(Double.parseDouble("0"));
        chart.getStyleManager().setLegendVisible(false);
        chart.getStyleManager().setLegendPosition(StyleManager.LegendPosition.InsideN);
        chart.addSeries("median", DoublesToCollection.toCollection(ColumnLoader.load(filename, "readIndex", "\t")), DoublesToCollection.toCollection(ColumnLoader.load(filename, "median", "\t")));

        chart.addSeries("25%", DoublesToCollection.toCollection(ColumnLoader.load(filename, "readIndex", "\t")), DoublesToCollection.toCollection(ColumnLoader.load(filename, "25%-percentile", "\t")));

        chart.addSeries("75%", DoublesToCollection.toCollection(ColumnLoader.load(filename, "readIndex", "\t")), DoublesToCollection.toCollection(ColumnLoader.load(filename, "75%-percentile", "\t")));

      }
      if (chart != null) {
        charts.add(chart);
      }
      filenameIndex++;
      if (filenameIndex == numCharts) {
        filenameIndex = 0;
      }
    }
    return charts;
  }



  /**
   * Returns a JFrame with the charts that display the content of the files.
   */
  public static void view(String... filenames) {
    ArrayList<Chart> charts = buildCharts(filenames);
    CustomSwingWrapper wrapper = new CustomSwingWrapper(charts);
    wrapper.setOnClose(JFrame.DISPOSE_ON_CLOSE);
    wrapper.displayChartMatrix();

  }

  /**
   * Returns a JPanel with the charts that display the content of the files.
   */
  public static JPanel panel(String... filenames) {
    ArrayList<Chart> charts = buildCharts(filenames);
    CustomSwingWrapper wrapper = new CustomSwingWrapper(charts);
    return wrapper.getChartMatrixPanel();
  }

  public static void main(String[] args) {
    view(args);
  }


}
