package org.campagnelab.gobyweb.environment.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import jetbrains.mps.smodel.runtime.StaticScope;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {

  /*package*/ final ConceptDescriptor myConceptGobyWebLoader = new ConceptDescriptorBuilder("org.campagnelab.gobyweb.environment.structure.GobyWebLoader", MetaIdFactory.conceptId(0x27f97fd8caeb43a0L, 0xa73ff8ac957f3a17L, 0xa270129099aef0eL)).super_("org.campagnelab.nyosh.environment.structure.Loader").super_(MetaIdFactory.conceptId(0xf071fdb3faa4b8cL, 0x9f5e1da0a01466d5L, 0x2c0a04a5bf418de1L)).parents("org.campagnelab.nyosh.environment.structure.Loader").parentIds(MetaIdFactory.conceptId(0xf071fdb3faa4b8cL, 0x9f5e1da0a01466d5L, 0x2c0a04a5bf418de1L)).alias("GobyWeb Environment loader", "load the basic GobyWeb environment").create();
  /*package*/ final ConceptDescriptor myConceptGobyWebSource = new ConceptDescriptorBuilder("org.campagnelab.gobyweb.environment.structure.GobyWebSource", MetaIdFactory.conceptId(0x27f97fd8caeb43a0L, 0xa73ff8ac957f3a17L, 0xa270129099aef0fL)).super_("org.campagnelab.nyosh.environment.structure.EnvironmentSource").super_(MetaIdFactory.conceptId(0xf071fdb3faa4b8cL, 0x9f5e1da0a01466d5L, 0x2c0a04a5bf4194ddL)).parents("org.campagnelab.nyosh.environment.structure.EnvironmentSource").parentIds(MetaIdFactory.conceptId(0xf071fdb3faa4b8cL, 0x9f5e1da0a01466d5L, 0x2c0a04a5bf4194ddL)).alias("", "the GobyWeb runtime environment").staticScope(StaticScope.ROOT).create();

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptGobyWebLoader, myConceptGobyWebSource);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0g, conceptFqName)) {
      case 0:
        return myConceptGobyWebLoader;
      case 1:
        return myConceptGobyWebSource;
      default:
        return null;
    }
  }
  private static String[] stringSwitchCases_1htk8d_a0a0g = new String[]{"org.campagnelab.gobyweb.environment.structure.GobyWebLoader", "org.campagnelab.gobyweb.environment.structure.GobyWebSource"};
}
