package org.campagnelab.gobyweb.environment.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.UUID;
import jetbrains.mps.smodel.runtime.StaticScope;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {

  /*package*/ final ConceptDescriptor myConceptGobyWebLoader = new ConceptDescriptorBuilder("org.campagnelab.gobyweb.environment.structure.GobyWebLoader", MetaIdFactory.conceptId(new UUID(2880474005774222240L, -6395119525716608489L), 731554740237430542L)).super_("org.campagnelab.nyosh.environment.structure.Loader").super_(MetaIdFactory.conceptId(new UUID(1082869261932317580L, -6963095398150543659L), 3173353997360795105L)).parents("org.campagnelab.nyosh.environment.structure.Loader").parentIds(MetaIdFactory.conceptId(new UUID(1082869261932317580L, -6963095398150543659L), 3173353997360795105L)).alias("GobyWeb Environment loader", "load the basic GobyWeb environment").create();
  /*package*/ final ConceptDescriptor myConceptGobyWebSource = new ConceptDescriptorBuilder("org.campagnelab.gobyweb.environment.structure.GobyWebSource", MetaIdFactory.conceptId(new UUID(2880474005774222240L, -6395119525716608489L), 731554740237430543L)).super_("org.campagnelab.nyosh.environment.structure.EnvironmentSource").super_(MetaIdFactory.conceptId(new UUID(1082869261932317580L, -6963095398150543659L), 3173353997360796893L)).parents("org.campagnelab.nyosh.environment.structure.EnvironmentSource").parentIds(MetaIdFactory.conceptId(new UUID(1082869261932317580L, -6963095398150543659L), 3173353997360796893L)).alias("", "the GobyWeb runtime environment").staticScope(StaticScope.ROOT).create();

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptGobyWebLoader, myConceptGobyWebSource);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0g, conceptFqName)) {
      case 0:
        return myConceptGobyWebLoader;
      case 1:
        return myConceptGobyWebSource;
      default:
        return null;
    }
  }
  private static String[] stringSwitchCases_1htk8d_a0a0g = new String[]{"org.campagnelab.gobyweb.environment.structure.GobyWebLoader", "org.campagnelab.gobyweb.environment.structure.GobyWebSource"};
}
