package NYoSh.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.SNodePointer;

public class ConceptFunctionParameter_outputReader_Constraints extends BaseConstraintsDescriptor {
  public ConceptFunctionParameter_outputReader_Constraints() {
    super("NYoSh.structure.ConceptFunctionParameter_outputReader");
  }

  @Override
  public boolean hasOwnCanBeChildMethod() {
    return true;
  }

  @Override
  public boolean canBeChild(@Nullable SNode node, SNode parentNode, SNode link, SNode childConcept, final IOperationContext operationContext, @Nullable final CheckingNodeContext checkingNodeContext) {
    boolean result = static_canBeAChild(node, parentNode, link, childConcept, operationContext);

    if (!(result) && checkingNodeContext != null) {
      checkingNodeContext.setBreakingNode(canBeChildBreakingPoint);
    }

    return result;
  }

  public static boolean static_canBeAChild(SNode node, SNode parentNode, SNode link, SNode childConcept, final IOperationContext operationContext) {
    if (ListSequence.fromList(SNodeOperations.getChildren(parentNode)).contains(SNodeOperations.getNode("r:70e37d76-af49-4a32-9523-a01860ff8f1c(NYoSh.structure)", "8155370969620059061"))) {
      return false;
    }
    return true;
  }

  private static SNodePointer canBeChildBreakingPoint = new SNodePointer("r:bbce89e8-2bb0-4c95-b1b7-870a649b438d(NYoSh.constraints)", "8155370969620214261");
}
