package NYoSh.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;

public class EntryPointImplementation_Constraints extends BaseConstraintsDescriptor {
  public EntryPointImplementation_Constraints() {
    super("NYoSh.structure.EntryPointImplementation");
  }
}
