package org.campagnelab.textoutput.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Line_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Line_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.textoutput.structure.Line";
  }
}
