package org.campagnelab.textoutput.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class Phrase_Behavior {
  public static void init(SNode thisNode) {
    SPropertyOperations.set(thisNode, "text", "");
  }
}
