package org.campagnelab.nyosh.environment.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.generator.template.BaseMappingRuleContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.generator.template.IfMacroContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;

public class QueriesGenerated {
  public static boolean baseMappingRule_Condition_832023732041957624(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SNodeOperations.isInstanceOf(_context.getNode(), "org.campagnelab.nyosh.environment.structure.MapFileSource") || SNodeOperations.isInstanceOf(_context.getNode(), "org.campagnelab.nyosh.environment.structure.JVMSource");
  }

  public static Object propertyMacro_GetPropertyValue_1909878773477091810(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return _context.createUniqueName("parser", _context.getNode());
  }

  public static Object propertyMacro_GetPropertyValue_1909878773477100094(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return _context.createUniqueName("variables", _context.getNode());
  }

  public static Object propertyMacro_GetPropertyValue_8112761687167793571(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_1909878773477079939(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return _context.createUniqueName("parser", _context.getNode());
  }

  public static Object propertyMacro_GetPropertyValue_1909878773476925368(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return _context.createUniqueName("variables", _context.getNode());
  }

  public static Object propertyMacro_GetPropertyValue_3356917312211481521(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "variable", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_3356917312210593894(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "ref", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_2328891098886615909(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "envVariable", false), "name");
    // <node> 
  }

  public static Object propertyMacro_GetPropertyValue_8432452818701170794(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "filename");
  }

  public static boolean ifMacro_Condition_1909878773475657194(final IOperationContext operationContext, final IfMacroContext _context) {
    return SPropertyOperations.getBoolean(_context.getNode(), "exposeToCommands");
  }

  public static boolean ifMacro_Condition_1909878773475701788(final IOperationContext operationContext, final IfMacroContext _context) {
    return SPropertyOperations.getBoolean(_context.getNode(), "exposeToCommands");
  }

  public static SNode sourceNodeQuery_8432452818698496400(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "source", true);
  }

  public static SNode sourceNodeQuery_8112761687168398296(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "envVariable", false);
  }

  public static SNode sourceNodeQuery_224223098171324849(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "key", true);
  }

  public static SNode sourceNodeQuery_8432452818701037410(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "path", true);
  }

  public static Iterable sourceNodesQuery_5955265417290063043(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "sources", true);
  }
}
