package org.campagnelab.gobyweb.editor;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.descriptor.EditorAspectDescriptor;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditorComponent;

public class EditorAspectDescriptorImpl implements EditorAspectDescriptor {


  public Collection<ConceptEditor> getEditors(ConceptDescriptor descriptor) {
    switch (Arrays.binarySearch(stringSwitchCases_xbvbvu_a0a0b, descriptor.getConceptFqName())) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new ExecutablePluginScript_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new FileSetCheckExpression_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new FileSetFetchCommand_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new FileSetFetchExpression_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new FileSetPushCommand_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new FileSetPushExpression_Editor());
      case 6:
        return Collections.<ConceptEditor>singletonList(new PluginReference_Editor());
      case 7:
        return Collections.<ConceptEditor>singletonList(new PluginRegistry_Editor());
      case 8:
        return Collections.<ConceptEditor>singletonList(new PluginScript_Editor());
      case 9:
        return Collections.<ConceptEditor>singletonList(new PluginSystemRootDirectory_Editor());
      case 10:
        return Collections.<ConceptEditor>singletonList(new PluginTree_Editor());
      case 11:
        return Collections.<ConceptEditor>singletonList(new RunMpsScript_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }

  public Collection<ConceptEditorComponent> getEditorComponents(ConceptDescriptor descriptor, String editorComponentId) {
    return Collections.<ConceptEditorComponent>emptyList();
  }



  private static String[] stringSwitchCases_xbvbvu_a0a0b = new String[]{"org.campagnelab.gobyweb.structure.ExecutablePluginScript", "org.campagnelab.gobyweb.structure.FileSetCheckExpression", "org.campagnelab.gobyweb.structure.FileSetFetchCommand", "org.campagnelab.gobyweb.structure.FileSetFetchExpression", "org.campagnelab.gobyweb.structure.FileSetPushCommand", "org.campagnelab.gobyweb.structure.FileSetPushExpression", "org.campagnelab.gobyweb.structure.PluginReference", "org.campagnelab.gobyweb.structure.PluginRegistry", "org.campagnelab.gobyweb.structure.PluginScript", "org.campagnelab.gobyweb.structure.PluginSystemRootDirectory", "org.campagnelab.gobyweb.structure.PluginTree", "org.campagnelab.gobyweb.structure.RunMpsScript"};
}
