package org.campagnelab.gobyweb.plugins.test.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import org.campagnelab.gobyweb.plugins.test.behavior.DualFileSetArea_Behavior;
import org.campagnelab.gobyweb.plugins.test.behavior.PluginTestCase_Behavior;
import org.campagnelab.gobyweb.interactive.behavior.JobArea_Behavior;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;

@Generated
public class QueriesGenerated {
  public final boolean NEEDS_OPCONTEXT = false;

  public static Object propertyMacro_GetPropertyValue_1546477733290515288(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SNodeOperations.cast(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "configuration", true), "executionEnvironment", false), "jobArea", true), "org.campagnelab.gobyweb.plugins.test.structure.JobAreaWithSDK"), "SDKDirectory");
  }

  public static Object propertyMacro_GetPropertyValue_2726670175338787560(final PropertyMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, SNodeOperations.cast(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "configuration", true), "executionEnvironment", false), "pluginRepository", true), "org.campagnelab.gobyweb.interactive.structure.DualPluginRepository"), "virtual_getRemotePluginRepoPath_6985991452103701097", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_2726670175338063714(final PropertyMacroContext _context) {
    return DualFileSetArea_Behavior.call_getRemoteReference_2726670175338878707(SNodeOperations.cast(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "configuration", true), "executionEnvironment", false), "filesetArea", true), "org.campagnelab.gobyweb.plugins.test.structure.DualFileSetArea"));
  }

  public static Object propertyMacro_GetPropertyValue_1546477733293570829(final PropertyMacroContext _context) {
    StringBuilder builder = new StringBuilder();
    for (String arg : PluginTestCase_Behavior.call_generateArguments_3827903497680464580(_context.getNode())) {
      builder.append(arg).append(" ");
    }
    return builder.toString();
  }

  public static Object propertyMacro_GetPropertyValue_1546477733292638210(final PropertyMacroContext _context) {
    return JobArea_Behavior.call_getReference_2408108650476587028(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "configuration", true), "executionEnvironment", false), "jobArea", true));
  }

  public static Object propertyMacro_GetPropertyValue_1546477733292717210(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "configuration", true), "executionEnvironment", false), "owner", false), "id");
  }

  public static Object propertyMacro_GetPropertyValue_1546477733292705597(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "configuration", true), "assignedTag").charAt(0) + "/" + SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "configuration", true), "assignedTag");
  }

  public static Object propertyMacro_GetPropertyValue_5807598648179249173(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name") + "-submit";
  }

  public static Object propertyMacro_GetPropertyValue_827915552516181409(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name") + "-submit.sh";
  }

  public static Object propertyMacro_GetPropertyValue_827915552515310635(final PropertyMacroContext _context) {
    return JobArea_Behavior.call_getReference_2408108650476587028(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "configuration", true), "executionEnvironment", false), "jobArea", true));
  }

  public static Object propertyMacro_GetPropertyValue_827915552515346356(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "configuration", true), "executionEnvironment", false), "jobArea", true), "executionNode", false), "username") + "@" + SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "configuration", true), "executionEnvironment", false), "jobArea", true), "executionNode", false), "server");
  }

  public static Object propertyMacro_GetPropertyValue_827915552515395263(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "configuration", true), "executionEnvironment", false), "jobArea", true), "workingDirectory");
  }

  public static Object propertyMacro_GetPropertyValue_827915552516193547(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name") + "-submit.sh";
  }

  public static Object propertyMacro_GetPropertyValue_827915552515395929(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "configuration", true), "executionEnvironment", false), "jobArea", true), "workingDirectory");
  }

  public static Object propertyMacro_GetPropertyValue_827915552516199740(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name") + "-submit.sh";
  }

  public static Object propertyMacro_GetPropertyValue_827915552517259508(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "configuration", true), "executionEnvironment", false), "jobArea", true), "executionNode", false), "username") + "@" + SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "configuration", true), "executionEnvironment", false), "jobArea", true), "executionNode", false), "server");
  }

  public static Object propertyMacro_GetPropertyValue_827915552517259539(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "configuration", true), "executionEnvironment", false), "jobArea", true), "workingDirectory");
  }

  public static Object propertyMacro_GetPropertyValue_827915552517259554(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name") + "-submit.sh";
  }

  public static Object propertyMacro_GetPropertyValue_827915552515297748(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name") + "-copy";
  }

  public static Object propertyMacro_GetPropertyValue_1546477733304743021(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "slot", true), "ref", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_1171932074421(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SNodeOperations.getAncestor(_context.getNode(), "org.campagnelab.gobyweb.plugins.test.structure.PluginTestCase", false, false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_1546477733302960654(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SNodeOperations.getAncestor(_context.getNode(), "org.campagnelab.gobyweb.plugins.test.structure.PluginTestCase", false, false), "configuration", true), "assignedTag");
  }

  public static Object propertyMacro_GetPropertyValue_1546477733302962769(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(SNodeOperations.getAncestor(_context.getNode(), "org.campagnelab.gobyweb.plugins.test.structure.PluginTestCase", false, false), "configuration", true), "executionEnvironment", false), "jobArea", true), "brokerPortForJobs", false), "targetNode", false), "server");
  }

  public static Object propertyMacro_GetPropertyValue_1546477733302961409(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(SNodeOperations.getAncestor(_context.getNode(), "org.campagnelab.gobyweb.plugins.test.structure.PluginTestCase", false, false), "configuration", true), "executionEnvironment", false), "jobArea", true), "brokerPortForJobs", false), "number");
  }

  public static SNode sourceNodeQuery_1546477733303134410(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "body", true);
  }
}
