package org.campagnelab.gobyweb.plugins.test.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.PropertyMacroContext;
import org.campagnelab.gobyweb.plugins.test.behavior.PluginTestCase_Behavior;

@Generated
public class QueriesGenerated {
  public final boolean NEEDS_OPCONTEXT = false;

  public static Object propertyMacro_GetPropertyValue_3827903497683124194(final PropertyMacroContext _context) {
    StringBuilder builder = new StringBuilder();
    for (String arg : PluginTestCase_Behavior.call_generateArguments_3827903497680464580(_context.getNode())) {
      builder.append(arg).append(" ");
    }
    return builder.toString();
  }
}
