package BWAGobyArtifactPlugin;

/*Generated by MPS */

import org.campagnelab.nyosh.logging.StepsLoggerHelper;
import java.io.Writer;
import java.io.StringWriter;
import java.io.PrintWriter;

public class ErrorManagementImplementation {
  public void recordStepDone(String actionDescription) {
    StepsLoggingSuccessHandler_ym50rj_(actionDescription);

  }

  public void exception(String actionDescription, int statusCode, Exception exception) {
    StepsLoggingErrorHandler_kysnd9_(actionDescription, statusCode, exception);
  }



  public static void StepsLoggingErrorHandler_kysnd9_(String actionDescription, int statusCode, Exception exception) {
    StepsLoggerHelper.createLogFile();
    if (exception != null) {
      Writer stringW = new StringWriter();
      PrintWriter printW = new PrintWriter(stringW);
      exception.printStackTrace(printW);
      StepsLoggerHelper.assertTrue(false, "A step failed. Action: " + actionDescription + ". StackTrace: " + stringW.toString());
    } else {
      StepsLoggerHelper.assertTrue(false, "A step failed. Action: " + actionDescription);
    }
  }

  public static void StepsLoggingSuccessHandler_ym50rj_(String actionDescription) {
    StepsLoggerHelper.createLogFile();
    StepsLoggerHelper.done("Step successfully completed: " + actionDescription, 0);
  }


}
