package NYoSh.sandbox.Working;

/*Generated by MPS */


public class TestScript {
  public static void main(String[] arguments) {

    System.out.println("path:" + new PathPatternMatcher5("*.xml").resolve());
  }




}
