package NYoSh.sandbox.Working;

/*Generated by MPS */


public class Test10 {
  public static void main(String[] arguments) {
    if ("main".equals(arguments[0])) {
      String[] reducedArgs = new String[arguments.length - 1];
      if (arguments.length - 1 > 0) {
        System.arraycopy(arguments, 1, reducedArgs, 0, arguments.length - 1);
      }
      RawArgParser parser = (((RawArgParser) new RawArgParser()));
      IParsedArguments parsedArgs = parser.parse(reducedArgs);
      main(parsedArgs);

    }

    System.out.println("");



  }




  /*package*/ static void main(IParsedArguments args) {
    System.out.println("");
  }


}
