package org.campagnelab.gobyweb.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.generator.template.BaseMappingRuleContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;
import jetbrains.mps.generator.template.ReferenceMacroContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import jetbrains.mps.generator.template.WeavingMappingRuleContext;

public class QueriesGenerated {
  public static boolean baseMappingRule_Condition_2829258213794790139(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), "prototype", true), "org.campagnelab.gobyweb.structure.AlignerAlignEntryPointPrototype");
  }

  public static boolean baseMappingRule_Condition_7901651670848671397(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), "prototype", true), "org.campagnelab.gobyweb.structure.ArtifactInstallEntryPointPrototype");
  }

  public static boolean baseMappingRule_Condition_3173353997343021425(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), "prototype", true), "org.campagnelab.gobyweb.structure.ArtifactAttributeValuesEntryPointPrototype");
  }

  public static boolean baseMappingRule_Condition_5493669862521808141(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SPropertyOperations.hasValue(_context.getNode(), "pluginKind", "aligners", "aligners");
  }

  public static boolean baseMappingRule_Condition_5493669862521844821(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SPropertyOperations.hasValue(_context.getNode(), "pluginKind", "analyses", "aligners");
  }

  public static boolean baseMappingRule_Condition_3173353997328972276(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SPropertyOperations.hasValue(_context.getNode(), "pluginKind", "tasks", "aligners");
  }

  public static boolean baseMappingRule_Condition_7901651670847193590(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SPropertyOperations.hasValue(_context.getNode(), "pluginKind", "resources", "aligners");
  }

  public static Object propertyMacro_GetPropertyValue_4279449414586765803(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return "script";
  }

  public static Object propertyMacro_GetPropertyValue_4279449414586081197(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return "script";
  }

  public static Object propertyMacro_GetPropertyValue_4279449414586778198(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return "script";
  }

  public static Object propertyMacro_GetPropertyValue_1072453283801121851(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "conceptName");
  }

  public static Object propertyMacro_GetPropertyValue_1072453283801109683(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "modelName");
  }

  public static Object propertyMacro_GetPropertyValue_3173353997349149223(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "scriptName");
  }

  public static Object propertyMacro_GetPropertyValue_1072453283801220145(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SNodeOperations.getConceptDeclaration(_context.getNode()), "name");
  }

  public static Object propertyMacro_GetPropertyValue_1072453283801235399(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SModelOperations.getModelName(SNodeOperations.getModel(_context.getNode()));
  }

  public static Object propertyMacro_GetPropertyValue_3173353997349904259(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "script", true), "name");
  }

  public static Object propertyMacro_GetPropertyValue_1072453283801309327(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString_def(_context.getNode(), "pluginKind", "aligners");
  }

  public static Object referenceMacro_GetReferent_2829258213794356622(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "implementation", true);
  }

  public static Object referenceMacro_GetReferent_3173353997342968557(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "implementation", true);
  }

  public static Object referenceMacro_GetReferent_3173353997344250828(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "implementation", true);
  }

  public static SNode sourceNodeQuery_5493669862521842193(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return _context.getTemplateNode();
  }

  public static SNode sourceNodeQuery_8245000766498880589(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return _context.getTemplateNode();
  }

  public static SNode sourceNodeQuery_8245000766499343533(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return _context.getTemplateNode();
  }

  public static SNode sourceNodeQuery_1072453283801354110(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return _context.getTemplateNode();
  }

  public static SNode weaving_MappingRule_ContextNodeQuery_2829258213791617280(final IOperationContext opereationContext, final WeavingMappingRuleContext _context) {
    return SNodeOperations.getAncestor(_context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "parseArguments"), "jetbrains.mps.baseLanguage.structure.StatementList", false, false);
  }

  public static SNode weaving_MappingRule_ContextNodeQuery_7901651670848671386(final IOperationContext opereationContext, final WeavingMappingRuleContext _context) {
    return SNodeOperations.getAncestor(_context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "parseArguments"), "jetbrains.mps.baseLanguage.structure.StatementList", false, false);
  }

  public static SNode weaving_MappingRule_ContextNodeQuery_3173353997343021414(final IOperationContext opereationContext, final WeavingMappingRuleContext _context) {
    return SNodeOperations.getAncestor(_context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "parseArguments"), "jetbrains.mps.baseLanguage.structure.StatementList", false, false);
  }
}
