package org.campagnelab.gobyweb.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.generator.template.BaseMappingRuleContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.generator.template.IfMacroContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;

public class QueriesGenerated {
  public static boolean baseMappingRule_Condition_5493669862521808141(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SPropertyOperations.hasValue(_context.getNode(), "pluginKind", "aligners", "aligners");
  }

  public static boolean baseMappingRule_Condition_5493669862521844821(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SPropertyOperations.hasValue(_context.getNode(), "pluginKind", "analyses", "aligners");
  }

  public static boolean baseMappingRule_Condition_3173353997328972276(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SPropertyOperations.hasValue(_context.getNode(), "pluginKind", "tasks", "aligners");
  }

  public static boolean baseMappingRule_Condition_7901651670847193590(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SPropertyOperations.hasValue(_context.getNode(), "pluginKind", "resources", "aligners");
  }

  public static Object propertyMacro_GetPropertyValue_4279449414586765803(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return "script";
  }

  public static Object propertyMacro_GetPropertyValue_4279449414586081197(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return "script";
  }

  public static Object propertyMacro_GetPropertyValue_4279449414586778198(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return "script";
  }

  public static Object propertyMacro_GetPropertyValue_1072453283801109683(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "modelName");
  }

  public static Object propertyMacro_GetPropertyValue_3173353997349149223(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "scriptName");
  }

  public static Object propertyMacro_GetPropertyValue_1072453283801220145(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SNodeOperations.getConceptDeclaration(_context.getNode()), "name");
  }

  public static Object propertyMacro_GetPropertyValue_1072453283801235399(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SModelOperations.getModelName(SNodeOperations.getModel(_context.getNode()));
  }

  public static Object propertyMacro_GetPropertyValue_3173353997349904259(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return ((SLinkOperations.getTarget(_context.getNode(), "script", true) == null) ?
      "invalid script for plugin " + SPropertyOperations.getString(_context.getNode(), "pluginId") :
      SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "script", true), "name")
    );
  }

  public static Object propertyMacro_GetPropertyValue_1072453283801309327(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString_def(_context.getNode(), "pluginKind", "aligners");
  }

  public static Object propertyMacro_GetPropertyValue_1909878773477113383(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return _context.createUniqueName("parser", _context.getNode());
  }

  public static Object propertyMacro_GetPropertyValue_1909878773477119757(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return _context.createUniqueName("variables", _context.getNode());
  }

  public static Object propertyMacro_GetPropertyValue_4384389959129878490(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "input", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_4384389959132330978(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "output", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_6046624752558723768(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "input", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_1428468125944699(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "output", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_1428468129703572(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "input", false), "name");
  }

  public static boolean ifMacro_Condition_1909878773475701788(final IOperationContext operationContext, final IfMacroContext _context) {
    return SPropertyOperations.getBoolean(_context.getNode(), "exposeToCommands");
  }

  public static SNode sourceNodeQuery_5493669862521842193(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return _context.getTemplateNode();
  }

  public static SNode sourceNodeQuery_8245000766498880589(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return _context.getTemplateNode();
  }

  public static SNode sourceNodeQuery_8245000766499343533(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return _context.getTemplateNode();
  }

  public static SNode sourceNodeQuery_1072453283801354110(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return _context.getTemplateNode();
  }

  public static SNode sourceNodeQuery_4384389959129854621(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "command", true);
  }

  public static SNode sourceNodeQuery_4384389959132330969(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "command", true);
  }

  public static SNode sourceNodeQuery_4384389959133729632(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "pathpattern", true);
  }

  public static SNode sourceNodeQuery_6046624752558723427(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "command", true);
  }

  public static SNode sourceNodeQuery_1428468125944691(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "command", true);
  }

  public static SNode sourceNodeQuery_1428468125975321(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "pathpattern", true);
  }

  public static SNode sourceNodeQuery_1428468129703564(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "command", true);
  }
}
