package org.campagnelab.gobyweb.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.generator.template.BaseMappingRuleContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;

public class QueriesGenerated {
  public static boolean baseMappingRule_Condition_5493669862521808141(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SPropertyOperations.hasValue(_context.getNode(), "pluginKind", "aligners", "aligners");
  }

  public static boolean baseMappingRule_Condition_5493669862521844821(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SPropertyOperations.hasValue(_context.getNode(), "pluginKind", "analyses", "aligners");
  }

  public static boolean baseMappingRule_Condition_5493669862521506277(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SPropertyOperations.hasValue(_context.getNode(), "pluginKind", "aligners", "aligners");
  }

  public static Object propertyMacro_GetPropertyValue_1072453283801109683(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "modelName");
  }

  public static Object propertyMacro_GetPropertyValue_1072453283801121851(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "conceptName");
  }

  public static Object propertyMacro_GetPropertyValue_1072453283801220145(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SNodeOperations.getConceptDeclaration(_context.getNode()), "name");
  }

  public static Object propertyMacro_GetPropertyValue_1072453283801235399(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SModelOperations.getModelName(SNodeOperations.getModel(_context.getNode()));
  }

  public static Object propertyMacro_GetPropertyValue_1072453283801309327(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString_def(_context.getNode(), "pluginKind", "aligners");
  }

  public static SNode sourceNodeQuery_5493669862521549855(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {

    return _context.getTemplateNode();
  }

  public static SNode sourceNodeQuery_5493669862521842193(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return _context.getTemplateNode();
  }

  public static SNode sourceNodeQuery_8245000766498880589(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return _context.getTemplateNode();
  }

  public static SNode sourceNodeQuery_8245000766499343533(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return _context.getTemplateNode();
  }

  public static SNode sourceNodeQuery_1072453283801354110(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return _context.getTemplateNode();
  }
}
