package NYoSh.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.ClassConcept_BehaviorDescriptor;

public class ArgumentParser_BehaviorDescriptor extends ClassConcept_BehaviorDescriptor {
  public ArgumentParser_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "NYoSh.structure.ArgumentParser";
  }
}
