package NYoSh.behavior;

/*Generated by MPS */


public class BinaryCommandOperator_BehaviorDescriptor extends AbstractCommand_BehaviorDescriptor {
  public BinaryCommandOperator_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "NYoSh.structure.BinaryCommandOperator";
  }
}
