package NYoSh.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.ConceptFunction_BehaviorDescriptor;

public class ConceptFunction_EntryPoint_BehaviorDescriptor extends ConceptFunction_BehaviorDescriptor {
  public ConceptFunction_EntryPoint_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "NYoSh.structure.ConceptFunction_EntryPoint";
  }
}
