package NYoSh.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.ConceptFunctionParameter_BehaviorDescriptor;
import jetbrains.mps.lang.core.behavior.IDontSubstituteByDefault_BehaviorDescriptor;

public class ConceptFunctionParameter_outputReader_BehaviorDescriptor extends ConceptFunctionParameter_BehaviorDescriptor implements IDontSubstituteByDefault_BehaviorDescriptor {
  public ConceptFunctionParameter_outputReader_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "NYoSh.structure.ConceptFunctionParameter_outputReader";
  }
}
