package NYoSh.behavior;

/*Generated by MPS */


public class ConsumeCommandOutputWithStream_BehaviorDescriptor extends ConsumeOutput_BehaviorDescriptor {
  public ConsumeCommandOutputWithStream_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "NYoSh.structure.ConsumeCommandOutputWithStream";
  }
}
