package NYoSh.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;

public class EntryPoint_Behavior {
  public static void init(SNode thisNode) {
    SPropertyOperations.set(thisNode, "name", "main");
    SLinkOperations.setTarget(thisNode, "implementation", SConceptOperations.createNewNode("NYoSh.structure.EntryPointImplementation", null), true);
  }

  public static SNode call_parsedResultTypeName_7275222926027477504(SNode thisNode) {
    return SLinkOperations.getTarget(ListSequence.fromList(SLinkOperations.getTargets(SLinkOperations.getTarget(thisNode, "implementation", true), "parameter", true)).first(), "type", true);
    // <node> 
  }

  public static String call_name_4897094796220494643(SNode thisNode) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(thisNode, "implementation", true), "name");
  }
}
