package NYoSh.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class EntryPointPrototype_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public EntryPointPrototype_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "NYoSh.structure.EntryPointPrototype";
  }
}
