package NYoSh.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.BaseMethodDeclaration_BehaviorDescriptor;
import jetbrains.mps.baseLanguage.behavior.IValidIdentifier_BehaviorDescriptor;
import jetbrains.mps.baseLanguage.behavior.HasAnnotation_BehaviorDescriptor;
import jetbrains.mps.baseLanguage.behavior.IBLDeprecatable_BehaviorDescriptor;
import jetbrains.mps.baseLanguage.behavior.IStatementListContainer_BehaviorDescriptor;
import jetbrains.mps.lang.core.behavior.IContainer_BehaviorDescriptor;
import jetbrains.mps.baseLanguage.behavior.IMethodLike_BehaviorDescriptor;
import jetbrains.mps.lang.traceable.behavior.TraceableConcept_BehaviorDescriptor;
import jetbrains.mps.lang.traceable.behavior.ScopeConcept_BehaviorDescriptor;
import jetbrains.mps.lang.core.behavior.ScopeProvider_BehaviorDescriptor;
import jetbrains.mps.baseLanguage.behavior.ITypeApplicable_BehaviorDescriptor;
import jetbrains.mps.lang.core.behavior.ImplementationContainer_BehaviorDescriptor;
import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;

public class EntryPointImplementation_BehaviorDescriptor extends BaseMethodDeclaration_BehaviorDescriptor implements IValidIdentifier_BehaviorDescriptor, HasAnnotation_BehaviorDescriptor, IBLDeprecatable_BehaviorDescriptor, IStatementListContainer_BehaviorDescriptor, IContainer_BehaviorDescriptor, IMethodLike_BehaviorDescriptor, TraceableConcept_BehaviorDescriptor, ScopeConcept_BehaviorDescriptor, ScopeProvider_BehaviorDescriptor, ITypeApplicable_BehaviorDescriptor, ImplementationContainer_BehaviorDescriptor, INamedConcept_BehaviorDescriptor {
  public EntryPointImplementation_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "NYoSh.structure.EntryPointImplementation";
  }
}
