package NYoSh.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Statement_BehaviorDescriptor;

public class ExecuteCommand_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public ExecuteCommand_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "NYoSh.structure.ExecuteCommand";
  }
}
