package NYoSh.behavior;

/*Generated by MPS */


public class GStringCommand_BehaviorDescriptor extends AbstractCommand_BehaviorDescriptor {
  public GStringCommand_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "NYoSh.structure.GStringCommand";
  }
}
