package NYoSh.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.smodel.behaviour.BehaviorManager;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class IEntryPointPrototype_Behavior {
  public static void init(SNode thisNode) {
  }

  @Deprecated
  public static List<SNode> call_parameters_2829258213786778419(SNode thisNode) {
    return BehaviorReflection.invokeVirtual((Class<List<SNode>>) ((Class) Object.class), thisNode, "virtual_parameters_2829258213786778419", new Object[]{});
  }

  @Deprecated
  public static List<SNode> callSuper_parameters_2829258213786778419(SNode thisNode, String callerConceptFqName) {
    return BehaviorManager.getInstance().invokeSuper((Class<List<SNode>>) ((Class) Object.class), SNodeOperations.cast(thisNode, "NYoSh.structure.IEntryPointPrototype"), callerConceptFqName, "virtual_parameters_2829258213786778419", new Class[]{SNode.class}, new Object[]{});
  }
}
