package NYoSh.behavior;

/*Generated by MPS */


public class PipeOutErrCommandOperator_BehaviorDescriptor extends BinaryCommandOperator_BehaviorDescriptor {
  public PipeOutErrCommandOperator_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "NYoSh.structure.PipeOutErrCommandOperator";
  }
}
