package NYoSh.behavior;

/*Generated by MPS */


public class PipeOutCommandOperator_BehaviorDescriptor extends BinaryCommandOperator_BehaviorDescriptor {
  public PipeOutCommandOperator_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "NYoSh.structure.PipeOutCommandOperator";
  }
}
