package NYoSh.behavior;

/*Generated by MPS */


public class PipeCommandOperator_BehaviorDescriptor extends BinaryCommandOperator_BehaviorDescriptor {
  public PipeCommandOperator_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "NYoSh.structure.PipeCommandOperator";
  }
}
