#This function is expected to an install the artifact in the given installation path
#Parameters:
# $1: the ID of the artifact to install as specified in the resource configuration
# $2: the target installation path
function plugin_install_artifact {
    #sample parameters reading
    ID=$1
    INSTALLATION_PATH=$2
    #invoke the model throught the script generated by RunMpsScript
    . ${JOB_DIR}/run_model.sh plugin_install_artifact ${ID} ${INSTALLATION_PATH}

}

#attribute logic
function get_attribute_values {

  #invoke the model through the script generated by RunMpsScript
  . ${JOB_DIR}/run_model.sh get_attribute_values

}


