package org.campagnelab.background.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.BaseMappingRuleContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.UUID;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.generator.template.IfMacroContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;

@Generated
public class QueriesGenerated {
  public final boolean NEEDS_OPCONTEXT = false;
  public static boolean baseMappingRule_Condition_8098307996398949788(final BaseMappingRuleContext _context) {
    // replace this statements when they occur within a backgroundableTask body with the final  
    // version 
    return (SNodeOperations.getNodeAncestor(_context.getNode(), MetaAdapterFactory.getConcept(new UUID(2366706908373403857l, -7418183695899801258l), 2434551981678775236l, "org.campagnelab.background.structure.BackgroundableTask"), false, false) != null);
  }
  public static Object propertyMacro_GetPropertyValue_2434551981679088017(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(new UUID(2366706908373403857l, -7418183695899801258l), 2434551981678775236l, 2434551981679075156l, "title"));
  }
  public static Object propertyMacro_GetPropertyValue_8912022532305770221(final PropertyMacroContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(new UUID(2366706908373403857l, -7418183695899801258l), 2434551981678775236l, 2434551981678849519l, "onCancel")) != null);
  }
  public static Object propertyMacro_GetPropertyValue_8912022532296043862(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(new UUID(2366706908373403857l, -7418183695899801258l), 2434551981678775236l, 2434551981679075156l, "title"));
  }
  public static Object propertyMacro_GetPropertyValue_8912022532303343236(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(new UUID(2366706908373403857l, -7418183695899801258l), 2434551981678775236l, 2434551981679075156l, "title"));
  }
  public static boolean ifMacro_Condition_2434551981679026277(final IfMacroContext _context) {
    return SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(new UUID(2366706908373403857l, -7418183695899801258l), 2434551981678775236l, 2434551981679124048l, "access")), MetaAdapterFactory.getConcept(new UUID(2366706908373403857l, -7418183695899801258l), 2434551981679124046l, "org.campagnelab.background.structure.WriteAccessType"));
  }
  public static boolean ifMacro_Condition_2434551981679042312(final IfMacroContext _context) {
    return SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(new UUID(2366706908373403857l, -7418183695899801258l), 2434551981678775236l, 2434551981679124048l, "access")), MetaAdapterFactory.getConcept(new UUID(2366706908373403857l, -7418183695899801258l), 2434551981679124041l, "org.campagnelab.background.structure.ReadAccessType"));
  }
  public static boolean ifMacro_Condition_8912022532306604724(final IfMacroContext _context) {
    return SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(new UUID(2366706908373403857l, -7418183695899801258l), 2434551981678775236l, 2434551981679124048l, "access")), MetaAdapterFactory.getConcept(new UUID(2366706908373403857l, -7418183695899801258l), 2434551981679124046l, "org.campagnelab.background.structure.WriteAccessType"));
  }
  public static boolean ifMacro_Condition_8912022532306604756(final IfMacroContext _context) {
    return SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(new UUID(2366706908373403857l, -7418183695899801258l), 2434551981678775236l, 2434551981679124048l, "access")), MetaAdapterFactory.getConcept(new UUID(2366706908373403857l, -7418183695899801258l), 2434551981679124041l, "org.campagnelab.background.structure.ReadAccessType"));
  }
  public static boolean ifMacro_Condition_572350672214579331(final IfMacroContext _context) {
    SNode enclosingMethod = SNodeOperations.getNodeAncestor(_context.getNode(), MetaAdapterFactory.getConcept(new UUID(-5808042798135555774l, -8657779246725685839l), 1225194472830l, "jetbrains.mps.lang.behavior.structure.ConceptMethodDeclaration"), false, false);
    return ((enclosingMethod != null) && SPropertyOperations.getBoolean(enclosingMethod, MetaAdapterFactory.getProperty(new UUID(-5808042798135555774l, -8657779246725685839l), 1225194472830l, 5864038008284099149l, "isStatic")));
  }
  public static SNode sourceNodeQuery_2434551981681904824(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(new UUID(2366706908373403857l, -7418183695899801258l), 2434551981678775236l, 2434551981678816405l, "task"));
  }
  public static SNode sourceNodeQuery_2434551981679022697(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(new UUID(2366706908373403857l, -7418183695899801258l), 2434551981678775236l, 2434551981678816407l, "onSuccess"));
  }
  public static SNode sourceNodeQuery_2434551981679042304(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(new UUID(2366706908373403857l, -7418183695899801258l), 2434551981678775236l, 2434551981678816407l, "onSuccess"));
  }
  public static SNode sourceNodeQuery_8912022532306604716(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(new UUID(2366706908373403857l, -7418183695899801258l), 2434551981678775236l, 2434551981678849519l, "onCancel"));
  }
  public static SNode sourceNodeQuery_8912022532306604748(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(new UUID(2366706908373403857l, -7418183695899801258l), 2434551981678775236l, 2434551981678849519l, "onCancel"));
  }
}
