package org.campagnelab.nyosh.gstring.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import java.util.Map;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.IScope;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class GStringLiteral_Constraints extends BaseConstraintsDescriptor {
  public GStringLiteral_Constraints() {
    super("org.campagnelab.nyosh.gstring.structure.GStringLiteral");
  }

  @Override
  protected Map<String, PropertyConstraintsDescriptor> getNotDefaultProperties() {
    Map<String, PropertyConstraintsDescriptor> properties = new HashMap();
    properties.put("value", new BasePropertyConstraintsDescriptor("value", this) {
      @Override
      public boolean hasOwnValidator() {
        return true;
      }

      @Override
      public boolean validateValue(SNode node, String propertyValue, IScope scope) {
        String propertyName = "value";
        if ((SPropertyOperations.getString(propertyValue)).contains("\"")) {
          int index = (SPropertyOperations.getString(propertyValue)).indexOf("\"");
        }
        return true;
      }
    });
    return properties;
  }
}
