package org.campagnelab.gobyweb.environment.behavior;

/*Generated by MPS */

import org.campagnelab.nyosh.environment.behavior.EnvironmentSource_BehaviorDescriptor;

public class GobyWebSource_BehaviorDescriptor extends EnvironmentSource_BehaviorDescriptor {
  public GobyWebSource_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.gobyweb.environment.structure.GobyWebSource";
  }
}
