package org.campagnelab.nyosh.pathpatterns.behavior;

/*Generated by MPS */

import org.campagnelab.nyosh.gstring.behavior.GString_BehaviorDescriptor;
import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.core.behavior.INamedConcept_Behavior;

public class Path_BehaviorDescriptor extends GString_BehaviorDescriptor implements INamedConcept_BehaviorDescriptor {
  public Path_BehaviorDescriptor() {
  }

  public String virtual_getFqName_1213877404258(SNode thisNode) {
    return INamedConcept_Behavior.virtual_getFqName_1213877404258(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.nyosh.pathpatterns.structure.Path";
  }
}
